[package]
name = "fast-layout"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Jinguo Liu <@GiggleLiu>"]
license = "MIT"
description = "Compute graph and tree layouts with a Rust engine."
compiler = "0.14.2"
categories = ["visualization"]
keywords = ["graph", "layout", "network", "tree"]
exclude = ["/tests/", "/manual.typ", "/manual.pdf", "/Makefile"]
